#!/usr/bin/env bash
# Displays the username, user id and home directory path from /etc/passwd
while IFS=: read -r username _ userid _ _ home _; do
    echo "$username:$userid:$home"
done < /etc/passwd
